- name: Provision lightsail client VM
  hosts: client
  vars_files:
    - vars.yml
  roles:
    - jmeter-client

- name: Provision lightsail server VMs
  hosts: servers
  vars_files:
    - vars.yml
  roles:
    - jmeter-client
    - jmeter-server
