---
- name: Start JMeter server in background
  shell: "nohup bin/jmeter-server -Djava.rmi.server.hostname=$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f8)  >/dev/null 2>&1 &"
  args:
    chdir: "~/apache-jmeter-{{ jmeter.version }}/"
