---
- name: Copy JMeter startup script
  template:
    src: jmeter.sh
    dest: "~/apache-jmeter-{{ jmeter.version }}/jmeter.sh"
    mode: 0755

- name: Start JMeter server
  shell: "~/apache-jmeter-{{ jmeter.version }}/jmeter.sh"
